### PR TITLE
Adding open console functionality

### PR DESCRIPTION
**Pull request by tristanmorgan**
HI @zwily,
This change adds the ability to open the AWS Console in the default browser. Also bumps the version number.

### CODE REVIEW

**Comment by landonwilkins** [comment]
yuss! version bump!

**Comment by zwily** [comment]
I have no idea how I missed this when it was submitted months ago. I'm gonna merge it soon after the break. Thanks!

**Comment by tristanmorgan** [comment]
Thanks @zwily, it will also help peoples access once its though to rubygems.

**Comment by tristanmorgan** [comment]
Rebased branch after version bump.

**Pull request closed without merging**
