### PR TITLE
AWS Assume role support

### PR DESCRIPTION
**Pull request by tristanmorgan**
HI @zwily ,

This builds on the AWS-SDK v2 work to add support to assume a role in either the current account or another account.

I can rebase it if you want to accept pull #15 first.

Cheers,

Tristan

### CODE REVIEW

**Comment by zwily** [comment]
Can you rebase now that https://github.com/zwily/aws-keychain-util/pull/15 is merged? Thanks.

**Comment by tristanmorgan** [comment]
Hi, I have rebased but not had time to separate the functional changes form the cosmetic (style) changes.
T.

**Comment by zwily** [comment]
Thanks!

**Comment by tristanmorgan** [comment]
Hi @zwily ,
Is it time for a version bump?
Regards,

T.

**Pull request merged**
