### PR TITLE
Migrate to the AWS-SDK v2

### PR DESCRIPTION
**Pull request by tristanmorgan**
Hi @zwily This pull request updated the gem to use the AWS-SDK v2 gem and a second commit that is just style changes made by Rubocop. I can drop the second one if you would rather just the functional change.

### CODE REVIEW

**Comment by tristanmorgan** [comment]
P.S. This pull request removes the need of pull request #11

**Comment by zwily** [comment]
@tristanmorgan Sorry for the delay here. I'd love to merge this, but would prefer the rubocop commit be separate if you don't mind. A travis config and a rake task so the rubocopping is automatic would be nice too.

**Comment by tristanmorgan** [comment]
Hi @zwily I have dropped the Rubocop commit and rebased the branch.

**Comment by zwily** [comment]
Thanks! Seems to work for me.

**Pull request merged**
